tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: site_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Site title'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: site_description
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Site description'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: site_logo
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Site logo'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: site_author
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Site author'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            import: social_links
          -
            handle: copyright
            field:
              antlers: true
              type: textarea
              display: Copyright
              listable: false
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: Design
        fields:
          -
            handle: theme
            field:
              options:
                theme-lighthouse: Lighthouse
              taggable: false
              push_tags: false
              multiple: false
              clearable: true
              searchable: true
              cast_booleans: false
              type: select
              display: Theme
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: typography
            field:
              options:
                prose-lighthouse: Lighthouse
              taggable: false
              push_tags: false
              multiple: false
              clearable: true
              searchable: true
              cast_booleans: false
              type: select
              display: Typography
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: Meta-Informations
        fields:
          -
            handle: meta_informations_icons
            field:
              antlers: false
              type: textarea
              display: Icons
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: meta_informations_cookie_banner
            field:
              antlers: false
              type: textarea
              display: Cookie-Banner
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: meta_informations_google_analytics
            field:
              antlers: false
              type: textarea
              display: 'Google Analytics'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: meta_informations_rss_feed
            field:
              input_type: text
              antlers: false
              type: text
              display: RSS-Feed
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  header:
    display: Header
    sections:
      -
        fields:
          -
            handle: header_show_site_title
            field:
              default: false
              type: toggle
              display: 'Show site title'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: header_top_bar
            field:
              type: section
              display: 'Top Bar'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: header_top_bar_text
            field:
              input_type: text
              antlers: true
              type: text
              display: Text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: buttons
  footer:
    display: Footer
    sections:
      -
        fields:
          -
            handle: contact_form
            field:
              type: section
              display: 'Contact Form'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: footer_contact_form_title
            field:
              input_type: text
              antlers: false
              type: text
              display: Title
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: footer_contact_form_description
            field:
              antlers: true
              type: textarea
              display: Description
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
