title: Product
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Title
              instructions_position: above
              listable: true
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: subtitle
            field:
              input_type: text
              antlers: false
              type: text
              display: Subtitle
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: excerpt
            field: markdown.markdown
            config:
              display: Excerpt
          -
            handle: content
            field: bard.content
          -
            handle: layout
            field:
              hide_partials: true
              blueprint: false
              type: template
              display: Layout
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: template
            field:
              hide_partials: true
              blueprint: false
              type: template
              display: Template
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
                - 'max:200'
              display: Slug
              instructions_position: above
              listable: true
              visibility: visible
              replicator_preview: true
              from: title
              generate: true
              show_regenerate: true
              hide_display: false
          -
            handle: product_image
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Product Image'
              listable: true
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: background_color
            field: background.background_color
          -
            handle: featured_image
            field:
              max_files: 1
              mode: grid
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Featured Image'
              listable: true
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  SEO:
    display: SEO
    sections:
      -
        fields:
          -
            handle: seo
            field:
              type: seo_pro
              listable: false
              display: SEO
